name: Code Quality

on: [push, pull_request]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pylint

      - name: Run Ruff (Lint + Fix)
        run: ruff check . --fix

      - name: Run Black (Check format)
        run: black --check .

      - name: Run Pylint
        run: pylint $(git ls-files '*.py')
